name: Build & Push (API)
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:latest
          IMAGE_SHA=ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker build -t "$IMAGE" -t "$IMAGE_SHA" .

      - name: Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:latest
          IMAGE_SHA=ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push "$IMAGE"
          docker push "$IMAGE_SHA"
      
      - name: Get digest
        id: digest
        run: |
          DIGEST=$(crane digest ghcr.io/${{ github.repository }}:${{ github.sha }})
          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT
      
      - name: Notify ops repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.OPSPROD_DISPATCH_TOKEN }}
          repository: itshukychen/investment-ops
          event-type: image-published
          client-payload: >
            { "service": "pp-api",
              "image": "ghcr.io/${{ github.repository }}:${{ github.sha }}",
              "digest": "${{ steps.push.outputs.digest }}" }
