name: Build & Push (API)
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:latest
          IMAGE_SHA=ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker build -t "$IMAGE" -t "$IMAGE_SHA" .

      - name: Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:latest
          IMAGE_SHA=ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push "$IMAGE"
          docker push "$IMAGE_SHA"

